apiVersion: v2
name: opensource-metrics-and-tracing
description: Opensource metrics and tracing solution using OTEL for collection , Tempo as tracing backend , Mimir as metrics backend and Grafana for visualization
version: 0.0.2
dependencies:
  - name: grafana
    version: "7.3.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: mimir-distributed
    alias: mimir
    version: "5.2.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: mimir.enabled
  - name: tempo-distributed
    alias: tempo
    version: "1.8.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled
  - name: opentelemetry-collector 
    alias: collector
    version: "0.80.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: collector.enabled
  - name: opentelemetry-collector 
    alias: cluster-events-collector
    version: "0.80.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: cluster-events-collector.enabled
  - name: opentelemetry-collector 
    alias: cluster-metrics-collector
    version: "0.80.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: cluster-metrics-collector.enabled
