apiVersion: v2
name: observability-opensource-complete
description: A fully integrated observability stack for Kubernetes applications using OpenTelemetry and Grafana.
version: 0.0.1
dependencies:
  - name: grafana
    version: "7.3.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: mimir-distributed
    alias: mimir
    version: "5.2.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: mimir.enabled
  - name: tempo-distributed
    alias: tempo
    version: "1.8.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled
  - name: loki-distributed
    alias: loki-distributed
    version: "0.78.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki-distributed.enabled
  - name: loki
    alias: loki
    version: "5.42.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  - name: opentelemetry-collector 
    alias: collector
    version: "0.80.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: collector.enabled
  - name: opentelemetry-collector 
    alias: cluster-events-collector
    version: "0.80.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: cluster-events-collector.enabled
  - name: opentelemetry-collector 
    alias: logs-collection
    version: "0.80.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: logs-collection.enabled
  - name: opentelemetry-collector 
    alias: cluster-metrics-collector
    version: "0.80.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: cluster-metrics-collector.enabled
