{{- if .Values.observabilityIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koala-observability
  annotations:
    {{- toYaml .Values.observabilityIngress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.observabilityIngress.host }}
      http:
        paths:
          {{- range .Values.observabilityIngress.paths }}
          - path: "{{ tpl .path $ }}"
            pathType: Prefix
            backend:
              service:
                name: "{{ tpl .service.name $ }}"
                port:
                  number: {{ .service.port }}
          {{- end }}
{{- end }}