# TODO: Reduce permissions to only what is needed. This is partly copied from somewhere and does not necessarily reflect what we actually need.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "koala-agent.serviceAccountName" . }}
  {{- if hasKey .Release "Namespace" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - watch
    - list
    # Required for automating deletion of ephemeral/preview environments. 
    # Agent is hardcoded to only allow deleting namespaces prefixed with "preview-" or "ephemeral-".
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    - pods
    - replicationcontrollers
    - services
    - configmaps
    - nodes
    - persistentvolumes
    - persistentvolumeclaims
    - serviceaccounts
    - endpoints
    - limitranges
    - podtemplates
    - resourcequotas
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - rbac
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - clusterrolebindings
    - rolebindings
    - roles
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    - controllerrevisions
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - extensions
    resources:
    - ingresses
    - networkpolicies
    - ingressclasses
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    - ingressclasses
    - networkpolicies
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    verbs:
    - "get"
    - "list"
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    - csidrivers
    - csinodes
    - csistoragecapacities
    - volumeattachments
    verbs:
    - get
    - watch
    - list
  # Required to validate if enabled CRDs are enabled on cluster
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - watch
    - list
  # API groups with view access for various supported CRDs
  - apiGroups:
    - external-secrets.io # External Secrets
    - monitoring.googleapis.com # Stackdriver / GCP Monitoring
    - monitoring.coreos.com # Prometheus
    - monitoring.grafana.com # Grafana
    - argoproj.io # Argo CD/Workflows/Events/Rollouts
    resources:
    - '*'
    verbs:
    - get
    - watch
    - list
  # Partial permissions for Cert Manager 
  - apiGroups:
    - cert-manager.io
    resources:
    - issuers
    - clusterissuers
    - certificaterequests
    - challenges
    - orders
    - certificates
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - metrics.k8s.io
    resources:
    - nodes
    - pods
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - authorization.k8s.io
    resources:
    - localsubjectaccessreviews
    - selfsubjectaccessreviews
    - selfsubjectrulesreviews
    - subjectaccessreviews
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - certificates.k8s.io
    resources:
    - certificatesigningrequests
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - flowcontrol.apiserver.k8s.io
    resources:
    - flowschemas
    - prioritylevelconfigurations
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - node.k8s.io
    resources:
    - runtimeclasses
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    - podsecuritypolicies
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - scheduling.k8s.io
    resources:
    - priorityclasses
    verbs:
    - get
    - watch
    - list
  # - apiGroups:
  #     - ""
  #   resources:
  #     - secrets
  #   verbs:
  #     - create
  #     - update
  #     - delete
  #     - list
  #     - get
  #     - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "koala-agent.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "koala-agent.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "koala-agent.serviceAccountName" . }}
    {{- if hasKey .Release "Namespace" }}
    namespace: {{ .Release.Namespace }}
    {{- end }}
---
