{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "koala-agent.name" . }}-secret
  {{- if hasKey .Release "Namespace" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
type: Opaque
data:
  KOALA_API_KEY: {{ .Values.apiKey | required "apiKey is a required value!" | b64enc }}
{{- end }}