{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "koala-agent.name" . }}-secret
  {{- if hasKey .Release "Namespace" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "koala-agent.labels" . | nindent 4 }}
  annotations:
    # This annotation ensures the secret is recreated on helm upgrade
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  KOALA_API_KEY: {{ .Values.apiKey | required "apiKey is a required value!" | b64enc }}
{{- end }}